"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Which env file to read, relative to the repo root: '.env.local.local' (local
# Postgres container, the default) or '.env.local.azure' (the shared dev databases on
# Azure). A missing file is a no-op, which is what we want on Azure App Service,
# where the values come from Application Settings instead. Real environment
# variables always win over the file, so a one-off override still works:
# `DB_SSLMODE=require python manage.py migrate`.
load_dotenv(BASE_DIR.parent / os.environ.get('DJANGO_ENV_FILE', '.env.local'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ["DJANGO_DEBUG"].lower() == "true"

def _csv_env(name):
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]

ALLOWED_HOSTS = _csv_env('DJANGO_ALLOWED_HOSTS')

CORS_ALLOWED_ORIGINS = _csv_env('CORS_ALLOWED_ORIGINS')

CSRF_TRUSTED_ORIGINS = _csv_env('CSRF_TRUSTED_ORIGINS')

# The session cookie is the whole authentication story (see core/authentication.py),
# so the browser has to be willing to send it on cross-origin fetches.
CORS_ALLOW_CREDENTIALS = True

# Rejected requests get JSON instead of Django's HTML page, because every caller
# here is a fetch() that cannot read HTML — see core/csrf.py.
CSRF_FAILURE_VIEW = 'core.csrf.csrf_failure'

# JS has to read the CSRF cookie to echo it back in the X-CSRFToken header,
# so this one cannot be HttpOnly. The session cookie stays HttpOnly (Django's
# default) — that is the one worth protecting from XSS.
CSRF_COOKIE_HTTPONLY = False

# 'true' only when the frontend is served from a different site than the API
# (e.g. a static host talking to App Service). Browsers reject SameSite=None
# without Secure, so that pairing is not optional. Default 'false' fits both
# the vite dev proxy (same-origin) and a frontend served by Django itself.
if (os.environ.get('DJANGO_CROSS_SITE_COOKIES') or 'false').lower() == 'true':
    SESSION_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE = True
else:
    SESSION_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE = not DEBUG

# Only safe when every request reaches the app through a proxy that overwrites
# this header (Azure App Service does). Turn off for a directly-reachable server.
if (os.environ.get('DJANGO_USE_PROXY_SSL_HEADER') or 'true').lower() == 'true':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Azure Postgres requires SSL; a local dev container doesn't support it.
# `or` rather than a .get() default: the shipped .env.local.example sets an empty value.
DB_SSLMODE = os.environ.get('DB_SSLMODE') or 'require'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['USER_DB_NAME'],
        'USER': os.environ['USER_DB_USER'],
        'PASSWORD': os.environ['USER_DB_PASSWORD'],
        'HOST': os.environ['USER_DB_HOST'],
        'PORT': os.environ.get('USER_DB_PORT', '5432'),
        'OPTIONS': {'sslmode': DB_SSLMODE},
    },
    'medical': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['MEDICAL_DB_NAME'],
        'USER': os.environ['MEDICAL_DB_USER'],
        'PASSWORD': os.environ['MEDICAL_DB_PASSWORD'],
        'HOST': os.environ['MEDICAL_DB_HOST'],
        'PORT': os.environ.get('MEDICAL_DB_PORT', '5432'),
        'OPTIONS': {'sslmode': DB_SSLMODE},
    },
}

DATABASE_ROUTERS = ['core.routers.CoreDatabaseRouter']


# Cache
# https://docs.djangoproject.com/en/6.1/topics/cache/

#: The table `core/migrations/0008_throttle_cache_table.py` creates. It is the
#: one table in `user_db` that `scripts/database_setup.sql` does not declare:
#: it holds no domain data, and `test_schema_sync.py` compares that script
#: against `core.models` table by table, where a model-less table has nothing to
#: compare with.
THROTTLE_CACHE_TABLE = 'throttle_cache'

# Where the throttle counters live, and the only reason this project has a cache
# at all. Django's default is local-memory, which is per *process*: with N
# gunicorn workers every cap was worth N times what it says, and the one that
# bounds password guessing bounded nothing in particular — which worker answered
# is up to the load balancer, so an attacker got a fresh budget by retrying.
#
# DatabaseCache is the shared backend that needs no new infrastructure; there is
# no Redis in this deployment and adding one for a handful of counters would be
# a service to run, monitor and pay for. It lands on `user_db` because
# `core/routers.py` sends every non-`core` app label to `default`.
#
# Putting counters next to the PII is safe only because of what the keys hold:
# `core/throttling.py` writes an HMAC of the caller's address and of the
# submitted e-mail, never either value — see `HashedIdent`, which was written
# against exactly this move.
#
# MAX_ENTRIES is far above Django's default of 300 on purpose. DatabaseCache
# culls the table once it grows past it, and a culled row is a throttle counter
# reset to zero: the cap would fail open under load, which is precisely when it
# is the only thing standing there. At 20 000 rows an hour's worth of counters
# fits with room to spare, and the table is still trivially small.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': THROTTLE_CACHE_TABLE,
        'OPTIONS': {'MAX_ENTRIES': 20000},
    },
}


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

# The default permission is IsAuthenticated rather than DRF's own AllowAny, so an
# endpoint that declares none is closed instead of silently public. The three
# views that legitimately serve visitors opt out by hand.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.SessionUserAuthentication',
    ],
    # Two defaults, both closed. IsAuthenticated keeps a new endpoint private;
    # HasActiveConsents keeps it away from an account whose RODO consents are not
    # in force, which the app has no lawful basis to process anything for. The
    # handful of views that legitimately opt out use core.permissions.
    # CONSENT_EXEMPT rather than spelling the list out, so the exempt set stays
    # one grep — see the note in that module.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'core.permissions.HasActiveConsents',
    ],
    'UNAUTHENTICATED_USER': None,
    # Applied to the login/register endpoints only (core.throttling.AuthThrottle);
    # everything else is unthrottled. Counted in CACHES['default'] above, which
    # is database-backed precisely so these are one budget per deployment rather
    # than one per gunicorn worker.
    # 'auth' is the per-IP cap; 'login_account' is the per-account one, which is
    # what actually bounds password guessing — a botnet hands every attempt its
    # own address and its own 'auth' budget, but they all land on the same
    # account counter. 15/hour leaves room for a person who genuinely cannot
    # remember which password they used, while making guessing pointless.
    'DEFAULT_THROTTLE_RATES': {
        'auth': '10/min',
        'login_account': '15/hour',
        # Not a security cap but a capacity one — see ReportPdfThrottle.
        'report_pdf': '30/hour',
        # POST /api/account/password/ verifies the *current* password, which
        # makes it a second place to guess one — from a session someone left
        # open on a borrowed phone, where the attacker has the app but not the
        # password they need to take the account over. Its own scope rather than
        # 'auth': changing what bounds login guessing must not quietly change
        # what bounds this.
        'password_change': '10/hour',
        # The two forms where a specialist names a person by e-mail. Both give
        # one deliberately uninformative refusal, and this is what keeps that
        # refusal from being asked often enough to map the user table anyway —
        # see SpecialistInviteThrottle. A specialist taking on a new caseload
        # invites a handful of people a day, not sixty an hour.
        'specialist_invite': '60/hour',
    },
    # How many proxies sit in front of us, and therefore how much of
    # X-Forwarded-For to believe. Unset, DRF keys the throttle on the *whole*
    # header — which the client writes, so a different value per request buys a
    # fresh 10/min budget every time and the cap counts nothing at all.
    #
    # 1 makes DRF read the last entry instead. Each proxy appends the address it
    # actually saw, so with exactly one hop in front (App Service) the last
    # entry is the real client and everything before it is whatever the caller
    # chose to claim. Raise this only if another proxy is added, and never lower
    # it to 0 while one is there: 0 means "trust REMOTE_ADDR", which behind a
    # proxy is the proxy, i.e. one budget shared by every client on the internet.
    'NUM_PROXIES': 1,
}

if not DEBUG:
    # The browsable API renders core.User objects and form widgets; useful while
    # developing, needless attack surface once deployed.
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = [
        'rest_framework.renderers.JSONRenderer',
    ]


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        # Django's default list is ('username', 'first_name', 'last_name',
        # 'email') — three of which core.User does not have, since it is a plain
        # domain model rather than an auth user. Without naming the real columns
        # the validator compares the password against `email` alone and silently
        # ignores the name it was given at registration.
        'OPTIONS': {'user_attributes': ('email', 'name', 'surname')},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# Polish, so that the messages Django itself produces (password validators,
# DRF field errors) reach the frontend in the same language as its own labels.
LANGUAGE_CODE = 'pl'

# Rows are stored in UTC either way (USE_TZ); this is what "today" means when a
# date is derived from a timestamp — which day a diary entry belongs to, and
# whether a date of birth is in the future. Everyone using this app is in Poland,
# and under UTC an entry written at 00:30 would count towards the previous day.
TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True


# Logging
# https://docs.djangoproject.com/en/6.1/topics/logging/

# Django's own default silences the console as soon as DEBUG is off: its handler
# carries a require_debug_true filter, and the only other one mails admins about
# ERRORs. A rejected CSRF check is a WARNING, so in production it reached nothing
# at all — the request 403'd without leaving a trace anywhere. App Service and
# gunicorn both collect stdout, so send it there unconditionally.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '{levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'loggers': {
        # propagate=False so DEBUG runs do not print every record twice, once
        # through this handler and once through the one Django set up.
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
