"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Which env file to read, relative to the repo root: '.env.local' (local
# Postgres container, the default) or '.env.azure' (the shared dev databases on
# Azure). A missing file is a no-op, which is what we want on Azure App Service,
# where the values come from Application Settings instead. Real environment
# variables always win over the file, so a one-off override still works:
# `DB_SSLMODE=require python manage.py migrate`.
load_dotenv(BASE_DIR.parent / os.environ.get('DJANGO_ENV_FILE', '.env.local'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ["DJANGO_DEBUG"].lower() == "true"

def _csv_env(name):
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]

ALLOWED_HOSTS = _csv_env('DJANGO_ALLOWED_HOSTS')

CORS_ALLOWED_ORIGINS = _csv_env('CORS_ALLOWED_ORIGINS')

CSRF_TRUSTED_ORIGINS = _csv_env('CSRF_TRUSTED_ORIGINS')

# The session cookie is the whole authentication story (see core/authentication.py),
# so the browser has to be willing to send it on cross-origin fetches.
CORS_ALLOW_CREDENTIALS = True

# JS has to read the CSRF cookie to echo it back in the X-CSRFToken header,
# so this one cannot be HttpOnly. The session cookie stays HttpOnly (Django's
# default) — that is the one worth protecting from XSS.
CSRF_COOKIE_HTTPONLY = False

# 'true' only when the frontend is served from a different site than the API
# (e.g. a static host talking to App Service). Browsers reject SameSite=None
# without Secure, so that pairing is not optional. Default 'false' fits both
# the vite dev proxy (same-origin) and a frontend served by Django itself.
if (os.environ.get('DJANGO_CROSS_SITE_COOKIES') or 'false').lower() == 'true':
    SESSION_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE = True
else:
    SESSION_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE = not DEBUG

# Only safe when every request reaches the app through a proxy that overwrites
# this header (Azure App Service does). Turn off for a directly-reachable server.
if (os.environ.get('DJANGO_USE_PROXY_SSL_HEADER') or 'true').lower() == 'true':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Azure Postgres requires SSL; a local dev container doesn't support it.
# `or` rather than a .get() default: the shipped .env.example sets an empty value.
DB_SSLMODE = os.environ.get('DB_SSLMODE') or 'require'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['USER_DB_NAME'],
        'USER': os.environ['USER_DB_USER'],
        'PASSWORD': os.environ['USER_DB_PASSWORD'],
        'HOST': os.environ['USER_DB_HOST'],
        'PORT': os.environ.get('USER_DB_PORT', '5432'),
        'OPTIONS': {'sslmode': DB_SSLMODE},
    },
    'medical': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['MEDICAL_DB_NAME'],
        'USER': os.environ['MEDICAL_DB_USER'],
        'PASSWORD': os.environ['MEDICAL_DB_PASSWORD'],
        'HOST': os.environ['MEDICAL_DB_HOST'],
        'PORT': os.environ.get('MEDICAL_DB_PORT', '5432'),
        'OPTIONS': {'sslmode': DB_SSLMODE},
    },
}

DATABASE_ROUTERS = ['core.routers.CoreDatabaseRouter']


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

# The default permission is IsAuthenticated rather than DRF's own AllowAny, so an
# endpoint that declares none is closed instead of silently public. The three
# views that legitimately serve visitors opt out by hand.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.SessionUserAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'UNAUTHENTICATED_USER': None,
    # Applied to the login/register endpoints only (core.views.AuthThrottle);
    # everything else is unthrottled. Counted in the default local-memory cache,
    # so the budget is per gunicorn worker rather than per deployment — a shared
    # cache backend is what would make this a real limit.
    'DEFAULT_THROTTLE_RATES': {'auth': '10/min'},
}

if not DEBUG:
    # The browsable API renders core.User objects and form widgets; useful while
    # developing, needless attack surface once deployed.
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = [
        'rest_framework.renderers.JSONRenderer',
    ]


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# Polish, so that the messages Django itself produces (password validators,
# DRF field errors) reach the frontend in the same language as its own labels.
LANGUAGE_CODE = 'pl'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
