# Generated by Django 6.1 on 2026-08-20 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id_diary', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_medical', models.UUIDField()),
                ('current_mood', models.TextField(blank=True, null=True)),
                ('current_strongest_emotion', models.TextField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('overall_feeling', models.TextField(blank=True, null=True)),
                ('situation', models.TextField(blank=True, null=True)),
                ('situation_place', models.TextField(blank=True, null=True)),
                ('how_situation_handled', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diary',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id_technique', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'technique',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id_user_role', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='MoodScale',
            fields=[
                ('id_scale', models.BigAutoField(primary_key=True, serialize=False)),
                ('sadness_scale', models.IntegerField(blank=True, null=True)),
                ('anxiety_scale', models.IntegerField(blank=True, null=True)),
                ('anger_scale', models.IntegerField(blank=True, null=True)),
                ('happiness_scale', models.IntegerField(blank=True, null=True)),
                ('guilt_scale', models.IntegerField(blank=True, null=True)),
                ('frustration_scale', models.IntegerField(blank=True, null=True)),
                ('helplessness_scale', models.IntegerField(blank=True, null=True)),
                ('diary', models.ForeignKey(blank=True, db_column='id_diary', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mood_scales', to='core.diary')),
            ],
            options={
                'db_table': 'mood_scale',
            },
        ),
        migrations.CreateModel(
            name='Specjalist',
            fields=[
                ('user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specjalist_profile', serialize=False, to='core.user')),
                ('specjalization', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specjalist',
            },
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id_parent_child', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child', models.ForeignKey(blank=True, db_column='id_child', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='core.user')),
                ('parent', models.ForeignKey(blank=True, db_column='id_parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to='core.user')),
            ],
            options={
                'db_table': 'parent_child',
            },
        ),
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id_raport', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_medical', models.UUIDField()),
                ('most_frequent_emotion', models.TextField(blank=True, null=True)),
                ('avg_mood', models.TextField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('number_of_bad_days', models.IntegerField(blank=True, null=True)),
                ('most_frequent_emotion_triggers', models.TextField(blank=True, null=True)),
                ('technique_efficiency', models.IntegerField(blank=True, null=True)),
                ('technique', models.ForeignKey(blank=True, db_column='id_technique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raports', to='core.technique')),
            ],
            options={
                'db_table': 'raport',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(blank=True, db_column='id_user_role', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.userrole'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_profile', serialize=False, to='core.user')),
                ('id_medical', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_child', models.BooleanField(blank=True, null=True)),
                ('specjalist', models.ForeignKey(blank=True, db_column='id_specjalist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.specjalist')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
