# Generated by Django 6.1 on 2026-08-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_align_faked_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='id_medical',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='raport',
            name='id_medical',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='parentchild',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='uniq_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='parentchild',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='parent_child_not_self'),
        ),
    ]
